version: "3"
services:
  influxdb:
    image: "influxdb:1.8"
    container_name: "influxdb"
    ports: ["8086:8086"]
    volumes:
      - "./docker-compose/influxdb:/docker-entrypoint-initdb.d:ro"
      - "influxdb-data:/var/lib/influxdb:rw"
    environment:
      INFLUXDB_REPORTING_DISABLED: "true"
volumes:
  influxdb-data:
